export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/tablescopia";
export * from "@/pages/dashboard/notifications";
export *from "@/pages/dashboard/tables";
export * from "@/pages/dashboard/roles";
export * from "@/pages/dashboard/departamentos";
export * from "@/pages/dashboard/divisiones";
export * from "@/pages/dashboard/ueducativas";
export * from "@/pages/dashboard/umilitares";
export * from "@/pages/dashboard/novedades";
export * from "@/pages/dashboard/partediaria";
export * from "@/pages/dashboard/informes";
