export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/tablescopia";
export * from "@/pages/dashboard/notifications";
export *from "@/pages/dashboard/tables";
export * from "@/pages/dashboard/roles";
export * from "@/pages/dashboard/partediaria";
export * from "@/pages/dashboard/vacaciones";
export * from "@/pages/dashboard/personalrrhh";
export * from "@/pages/dashboard/personal";
export * from "@/pages/dashboard/accesos";
export * from "@/pages/dashboard/novedades";
export * from "@/pages/dashboard/informes";
export * from "@/pages/dashboard/permisos";
export * from "@/pages/dashboard/parterrhh";
